### ISSUE TITLE
Predicates for ZonedDateTime

### ISSUE THREAD

**Issue by cneijenhuis** [sphereio/sphere-jvm-sdk#876] opened 2015-12-09 17:16 UTC
`ZonedDateTime` fields, e.g. `createdAt`, does have a `SortingModel`, but is not usable in predicates. E.g. I want to receive Messages that are less than an hour old.

```
MessageQuery.of()
  .withSort(m -> m.createdAt().sort().desc())
  .withPredicates(m -> m.createdAt(). ??? )
```

**Comment by schleichardt** [comment] 2015-12-09 18:18
This is a duplicate of https://github.com/sphereio/sphere-jvm-sdk/issues/743 .

I released some hours ago M23 which contains the predicates:

http://sphereio.github.io/sphere-jvm-sdk/javadoc/v1.0.0-M23/io/sphere/sdk/queries/TimestampSortingModel.html

**Closed by schleichardt** 2015-12-09 18:18 UTC
Labels: blocked, headache, question
