### ISSUE TITLE
Support update of product variants by sku

### ISSUE THREAD

**Issue by jayS-de** [sphereio/sphere-jvm-sdk#1111] opened 2016-04-20 16:05 UTC
See https://dev.commercetools.com/release-notes.html#release-2015-09-23

**Comment by schleichardt** [comment] 2016-04-20 17:33
duplicate of https://github.com/sphereio/sphere-jvm-sdk/issues/1023

Is there an urgent need? (if yes, ask in the older issue)

**Closed by schleichardt** 2016-04-20 17:33 UTC
Labels: duplicate, enhancement
