### ISSUE TITLE
Product suggestions search result not reproducible

### ISSUE THREAD

**Issue by twnexum** [sphereio/sphere-jvm-sdk#927] opened 2016-01-12 14:52 UTC
I am executing a search for product suggestions using the Java client 1.0.0-M25.

However, the search results are not reproducible: when I search for the same search term and the same locale, sometimes I get an empty search result, and sometimes I get search results.

I expect the Java client to return the same results for the same input when executed multiple times.

To illustrate the issue I wrote a simple unit test. When I execute this unit test, the assertion `Assert.assertTrue(!suggestionResult.getSuggestionsForLocale(locale).isEmpty());` pretty often fails.

```java
public class NxSphereSearchServiceImplTest3 {
	
	private static final Logger LOG = LoggerFactory.getLogger(NxSphereSearchServiceImplTest3.class);

	private SphereClient sphereClient;

	@Before
	public void startUp() {		
		SphereClientFactory factory = SphereClientFactory.of();
        this.sphereClient = factory.createClient("fachhaendler1", "xxxxxxxxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxxxxx");
	}
	
	@Test
	public void testProductSuggestions() throws Exception {
		
		// GIVEN
		Locale locale = Locale.GERMANY;
		int limit = 10;
		String keyword = "pegasu";
		
		// WHEN
		List<LocalizedStringEntry> searchKeywords = Collections.singletonList(LocalizedStringEntry.of(locale, keyword));		
		SuggestQuery sphereRequest = SuggestQuery.of(searchKeywords)
				.withLimit(limit)
				.withStaged(false);		
		
		// THEN
		SuggestionResult suggestionResult = sphereClient.execute(sphereRequest).toCompletableFuture().get();
		Assert.assertTrue(!suggestionResult.getSuggestionsForLocale(locale).isEmpty());
		
		List<String> result = new ArrayList<String>();
		suggestionResult.getSuggestionsForLocale(locale).forEach(suggestion -> {
			
			String text = suggestion.getText();
			result.add(text);
			if (LOG.isDebugEnabled()) {
				LOG.debug("Suggestion: " + text);
			}
		});
		
		Assert.assertTrue(result.contains("Pegasus"));
		Assert.assertTrue(result.contains("Pegasus Trekkingrad Solero SL"));
	}

}
```

**Comment by schleichardt** [comment] 2016-01-12 16:09
I cannot reproduce, this is my code:

```java
import io.sphere.sdk.client.BlockingSphereClient;
import io.sphere.sdk.client.SphereClientFactory;
import io.sphere.sdk.models.LocalizedString;
import io.sphere.sdk.models.LocalizedStringEntry;
import io.sphere.sdk.products.*;
import io.sphere.sdk.products.commands.ProductCreateCommand;
import io.sphere.sdk.products.commands.ProductUpdateCommand;
import io.sphere.sdk.products.commands.updateactions.Publish;
import io.sphere.sdk.products.queries.SuggestQuery;
import io.sphere.sdk.producttypes.ProductType;
import io.sphere.sdk.producttypes.ProductTypeDraft;
import io.sphere.sdk.producttypes.commands.ProductTypeCreateCommand;
import io.sphere.sdk.projects.Project;
import io.sphere.sdk.projects.queries.ProjectGet;
import io.sphere.sdk.search.SearchKeyword;
import io.sphere.sdk.search.SearchKeywords;
import io.sphere.sdk.search.tokenizer.WhiteSpaceSuggestTokenizer;
import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

import static java.util.Arrays.asList;

public class NxSphereSearchServiceImplTest3 {
    private static BlockingSphereClient sphereClient;

    @BeforeClass
    public static void startUp() {
        SphereClientFactory factory = SphereClientFactory.of();
        sphereClient = BlockingSphereClient.of(factory.createClient("tmp-issue-927", "ufqjVw0yIdFvHba8COZ3C6dW", "A54sNNF1h48cD-i3PI3HNyR1vclOsHpf"), 10, TimeUnit.SECONDS);
    }

    @AfterClass
    public static void stopClient() {
        sphereClient.close();
    }

    @Test
    public void testProductSuggestions() throws Exception {
        final Locale locale = Locale.GERMANY;

        final Project project = sphereClient.executeBlocking(ProjectGet.of());
        Assert.assertTrue("project is enabled for that language", project.getLanguages().contains(locale.toLanguageTag()));
        //maybe refresh product search in merchant center if you added a language https://admin.sphere.io/<YOUR_PROJECT_KEY>/developers/danger

        final ProductType productType = sphereClient.executeBlocking(ProductTypeCreateCommand.of(ProductTypeDraft.of(null, "name", "desc", Collections.emptyList())));
        final String germanName = "Pegasus Trekkingrad Solero SL";
        final LocalizedString name = LocalizedString.of(locale, germanName);
        final ProductVariantDraft masterVariant = ProductVariantDraftBuilder.of().build();
        final Product product = sphereClient.executeBlocking(ProductCreateCommand.of(ProductDraftBuilder.of(productType, name, name.slugifiedUnique(),
                masterVariant)
                .searchKeywords(SearchKeywords.of(locale, asList(SearchKeyword.of("Pegasus"), SearchKeyword.of(germanName, WhiteSpaceSuggestTokenizer.of()))))
                .build()));
        sphereClient.executeBlocking(ProductUpdateCommand.of(product, Publish.of()));


        final SuggestQuery sphereRequest = SuggestQuery.of(LocalizedStringEntry.of(locale, "pegasu")).withLimit(10);
        for(int i = 0; i < 100; i++) {
            final SuggestionResult suggestionResult = sphereClient.executeBlocking(sphereRequest);
            Assert.assertTrue("results are present", !suggestionResult.getSuggestionsForLocale(locale).isEmpty());
            final List<String> germanySuggestions = suggestionResult.getSuggestionsForLocale(locale).stream()
                    .map(Suggestion::getText)
                    .collect(Collectors.toList());
            Assert.assertTrue("Pegasus inside", germanySuggestions.contains("Pegasus"));
            Assert.assertTrue(germanName + " inside", germanySuggestions.contains(germanName));
        }
    }

}
```

**Comment by lauraluiz** [comment] 2016-01-12 16:49
@twnexum how do you create your test product? Are you creating the product every time? The fact that the result is empty makes me think it might have something to do with the eventual consistency of the product search endpoint.

**Comment by twnexum** [comment] 2016-01-13 06:17
Hello @lauraluiz , the product is not created every time. Please have a look at the code of the unit test.

**Comment by schleichardt** [comment] 2016-01-13 07:39
@twnexum could you reproduce your problem with my code? Is the problem still there?

**Comment by twnexum** [comment] 2016-01-13 07:55
Hello @schleichardt , at the moment I cannot reproduce the problem, but the problem was there (no joking).

Can you check your logs for product suggestion requests in the `fachhaendler1` project with search keywords `searchKeywords.de-DE=pegasu` to track the problem further down on the Sphere.IO side?

**Comment by yanns** [comment] 2016-01-13 08:59
@twnexum we have a lot of logs. Can you give us a time range?

**Comment by twnexum** [comment] 2016-01-13 09:01
Hello @yanns , January 12, 2016, 2pm - 4pm is the time range to have a look.

**Comment by yanns** [comment] 2016-01-13 09:20
I see that some products were deleted, created, published and unpublished at this time. Could it be the case of the observed problem?

I can send you the list of events if you want to. I prefer not to paste them here to protect the privacy of your data.

**Comment by schleichardt** [comment] 2016-01-13 14:45
We are now able to reproduce the problem and analyse it.

**Comment by twnexum** [comment] 2016-01-13 14:46
Wow, thank you!

**Comment by twnexum** [comment] 2016-01-18 12:38
Hello sphereio team, any news on this issue? Regards, Thomas

**Comment by stmeissner** [comment] 2016-01-18 13:18
@twnexum we are still investigating to get to the root cause of the problem. We'll let you know as soon as we know more.

**Comment by mmoelli** [comment] 2016-01-19 10:49
hey @twnexum 

Unfortunately, it's really hard to clearly reproduce this error on a constant level. Therefore we are currently not able see any patterns when or why this error is produced. Can you please provide us some more information?

- Is is still an ongoing issue for you?
- When is it happening?
- What were the last changes you made to your products?
- How many products/variants do you have in your data set when the issue occurs?
- Have you identified any patterns when this issue occured?

Thanks in advance!

**Comment by twnexum** [comment] 2016-01-19 11:26
I am sorry, but I cannot provide you any further information. I do not maintain the project, product types nor the products itself. With kind regards, Thomas

**Comment by stmeissner** [comment] 2016-03-03 10:25
Since we are not able to recreate the scenario for which the issue occurs we are going to close this issue for now.

**Closed by stmeissner** 2016-03-03 10:25 UTC
Labels: HTTP API related
